const express = require("express");
const router = express.Router();
const authRoutes = require("./userAuthRoutes");
const userRoutes = require("./userRoutes");
const clientRoutes = require("./clientRoutes");
const orderRoutes = require("./orderRoutes");
const productRoutes = require("./productRoutes");
const attendanceRoutes = require("./attendanceRoutes");
const expenseRoutes = require("./expenseRoutes");
const expenseTypeRoutes = require("./expenseTypeRoutes");
const collectionRoutes = require("./collectionRoutes");
const meetingRoutes = require("./meetingRoutes");
const notesRoutes = require("./noteRoutes");
const returnRoutes = require("./returnRoutes");
const taskRoutes = require("./taskRoutes");
const notificationRoutes = require("./notificationRoutes");
const messagesRoutes = require("./messageRoutes");
const adminRoutes = require("./adminAuthRoutes");
const rewardRoutes = require("./rewardsRoutes");
const leaderboardRoutes = require("./leaderboardRoutes");
const redeemRoutes = require("./redeemRoutes");
const performanceRoutes = require("./performanceRoutes");
const fieldStaffRoutes = require("./fieldStaffRoutes");
const locationRoutes = require("./locationRoutes");

router.use("/auth/user", authRoutes);
router.use("/auth/admin", adminRoutes);
router.use("/api/user", userRoutes);
router.use("/api/client", clientRoutes);
router.use("/api/order", orderRoutes);
router.use("/api/products", productRoutes);
router.use("/api/attendance", attendanceRoutes);
router.use("/api/expense", expenseRoutes);
router.use("/api/expenseType", expenseTypeRoutes);
router.use("/api/collections", collectionRoutes);
router.use("/api/meeting", meetingRoutes);
router.use("/api/notes", notesRoutes);
router.use("/api/return", returnRoutes);
router.use("/api/task", taskRoutes);
router.use("/api/notification", notificationRoutes);
router.use("/api/messages", messagesRoutes);
router.use("/api/rewards", rewardRoutes);
router.use("/api/leaderboard", leaderboardRoutes);
router.use("/api/redeem", redeemRoutes);
router.use("/api/performance", performanceRoutes);
router.use("/api/field-staff",fieldStaffRoutes);
router.use("/api/location",locationRoutes)

module.exports = router;
